### ISSUE TITLE
Temporary directory not included in docker path

### ISSUE THREAD

**Issue by ekilmer** [crytic/solc-select#8]
When trying to use solc-select with the automated integration tests for Manticore on Mac, there's an error that `solc` can't reach the working directory because it's in a temporary directory like 
```
""/var/folders/<2_chars>/<uuid>/T/tmpzos1e1fn"" is not found
```

I have patched the `bin/solc` docker invocation to also include:
```
--mount type=bind,source="/private/`getconf DARWIN_USER_TEMP_DIR`",target=`getconf DARWIN_USER_TEMP_DIR`
```
which fixes it, but I'm not sure how best to apply this so that Linux hosts don't get an error.

Furthermore, Linux temporary directory can be retrieved using
```
TMPDIR=`dirname $(mktemp -u -t tmp.XXXXXXXXXX)`
```
which can then be add as a mount too.

Also, for users that don't want to always include their temporary files, maybe we could have an environment variable to choose when to include the temporary directory in docker?

**Comment by ESultanik** [comment]
This is a known issue that (1) should have been better documented, and (2) really deserves a better solution. It is caused by the fact that `solc-select` only mounts `$PWD` in the Docker container. I think the ultimate solution would be to instead mount the root directory of the host system to `/host/` in the container, do something like `mount --bind /usr/bin /host/usr/bin`, and then `chroot /host/usr/bin`. That way `solc` in the container would have the same filesystem view as if it were running on the host. Would that solve your issue?

**Comment by ekilmer** [comment]
That does sound like it would solve my issue.
